name: 'cea_aw_franciscotaveira'
version: '1.0.0'
config-version: 2

profile: 'default'

# Definição dos diretórios usados no projeto
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cea_aw_franciscotaveira:

    # 🔹 Camada Staging (STG) - Transformação inicial
    staging:
      +schema: stg  # Criando o schema STG no Snowflake
      +materialized: view

      erp:
        +schema: stg
        +materialized: view

      crm:
        +schema: stg
        +materialized: view

      site:
        +schema: stg
        +materialized: view

      web_analytics:
        +schema: stg
        +materialized: view

    # 🔹 Camada Intermediate (INT) - Lógica de negócio, joins e métricas derivadas
    intermediate:
      +schema: int  # Criando o schema INT no Snowflake
      +materialized: view

    # 🔹 Camada Marts (MARTS) - Tabelas finais para consumo no BI
    marts:
      +schema: marts  # Criando o schema MARTS no Snowflake
      +materialized: table

