name: 'cea_aw_franciscotaveira'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cea_aw_franciscotaveira:

    # 🔹 Staging Layer (STG) - Standardization and cleaning
    staging:
      +schema: stg
      +materialized: view

      sales:
        +schema: stg
        +materialized: view
      
      production:
        +schema: stg
        +materialized: view

      person:
        +schema: stg
        +materialized: view

    # 🔹 Intermediate Layer (INT) - Business logic, joins, and transformations
    intermediate:
      +schema: int
      +materialized: view

    # 🔹 Marts Layer (MARTS) - Final tables for BI consumption
    marts:
      +schema: marts
      +materialized: table

    # 🔹 Test Layer - Validation models and assertions
    tests:
      +schema: test
      +materialized: table