name: 'cea_aw_franciscotaveira'
version: '1.0.0'
config-version: 2

profile: 'default'

# Definição dos diretórios usados no projeto
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cea_aw_franciscotaveira:

    # Camada Staging (Padronização inicial, sem joins ou agregações)
    staging:
      +schema: staging
      +materialized: table

    # Camada Intermediate (Aplicação de lógica de negócio, joins e métricas derivadas)
    intermediate:
      +schema: intermediate
      +materialized: table

    # Camada Marts (Tabelas finais para consumo no BI)
    marts:
      +schema: marts
      +materialized: table 

    # Categorias adicionais (se necessário, pode ser removido se não usado)
    erp:
      +schema: erp
      +materialized: table

    crm:
      +schema: crm
      +materialized: table

    site:
      +schema: site
      +materialized: table

    web_analytics:
      +schema: web_analytics
      +materialized: table
