name: 'cea_aw_franciscotaveira'
version: '1.0.0'
config-version: 2

profile: 'default'

# Definição dos diretórios usados no projeto
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cea_aw_franciscotaveira:
    staging:
      +schema: staging
      +materialized: view

    erp:
      +schema: erp
      +materialized: table

    crm:
      +schema: crm
      +materialized: table

    site:
      +schema: site
      +materialized: table

    web_analytics:
      +schema: web_analytics
      +materialized: table
